dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'Cargo.toml'
      - 'Cargo.lock'

maintenance:
  - branch: ['^chore']

enhancement:
  - changed-files:
    - any-glob-to-any-file:
      - 'rust/**/*.rs'
      - 'ts/src/**/*.rs'
  - branch: ["^feat", "^feature"]

wip:
  - branch: ['^wip/.*', '^dev/.*']
