ci:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*.yml'
      - '.github/workflows/**/*.yaml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'Cargo.toml'
      - 'Cargo.lock'

docs:
  - changed-files:
    - any-glob-to-any-file: '*.md'

generated:
  - changed-files:
    - any-glob-to-any-file:
      - 'ts/src/generated/**/*.ts'
      - 'types/**/*.d.ts'

maintenance:
  - changed-files:
    - any-glob-to-any-file:
      - 'rust/benches/**/*.rs'
      - 'ts/benchmarks/**/*.ts'
      - 'ts/tests/**/*.ts'
  - branch: ['^chore/.*']

enhancement:
  - changed-files:
    - any-glob-to-any-file:
      - 'rust/**/*.rs'
      - 'ts/src/**/*.ts'
  - branch: ["^feat/.*", "^feature/.*"]

bug:
  - branch: ['^fix/.*', '^bugfix/.*']

wip:
  - branch: ['^wip/.*', '^dev/.*']
