name: Release Please (No Auto-Tag)

on:
  push:
    branches:
      - main # atau 'master'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          # Triknya di sini: Kita paksa skip pembuatan GitHub Release/Tag
          skip-github-release: true 
