export default {
  version: '0.2',
  language: 'en',
  dictionaries: ['rust', 'rust-crates'],
  words: [
    'smol',
    'lightvm',
    'vmerror',
    'stdin',
    'stdinln',
    'stdout',
    'stdoutln',
    'print',
    'println',
    'napi',
    'synclean',
    'solas',
    'octa',
    'half',
    'integer',
    'float',
    'short',
    'double',
    'threadsafe',
    'vmevent',
    'vmstate',
    'unparseable',
    'acode',
    'unitry',
    'vmresult',
    'msvc',
    'spac',
    'trin',
    'unref',
    'accessindex',
    'vmconfig',
    'claycuy'
  ],
  ignorePaths: [
    'node_modules/**',
    'target/**',
    '**/target/**',
    'binaries/**',
    'types/**/*',
    'ts/src/generated/**/*',
    'scripts/**/*',
    'ts/benchmarks/**/*',
    'rust/benches/**/*',
  ],
};
