target_dir = "rust/src"
entry_file = "lib.rs"

[scripts.format]
desc = "Perform formatting on the code"
commands = ["clean", "header", "cargo fmt --all"]
[scripts.check]
desc = "Perform a check on the code"
commands = ["cargo clippy -- -D warnings"]
[scripts.perf]
desc = "Checking code performance"
commands = ["clean", "header", "track"]

# Commands for developers
[scripts.test-rust]
desc = "Running unit tests on .rs files"
commands = ["cargo test"]
[scripts.test-ts]
desc = "Running unit tests on .ts file$"
commands = ["node ./scripts/run-tests.js"]
[scripts.bench-rust]
desc = "To get benchmark results from Rust code"
commands = ["cargo bench"]
[scripts.bench-ts]
desc = "To get benchmark results from TypeScript code"
commands = ["node ./scripts/ts-bench.js"]
[scripts.build]
desc = "Generating build results from TypeScript source"
commands = ["node ./esbuild.config.js"]
[scripts.build-release]
desc = "Create a build release .tgz file"
commands = ["node ./scripts/build-script.js --local --silent"]
[scripts.build-debug]
desc = "Create a build debug .tgz file"
commands = ["node ./scripts/build-script.js --local --debug --silent"]
[scripts.check-deps]
desc = "Checking installed local dependencies"
commands = ["node ./scripts/check-deps.js"]
[scripts.typecheck]
desc = "Type checking"
commands = ["tsc"]
[scripts.prettier]
desc = "Formatting code"
commands = ["npx prettier ./ts/**/*.ts --write"]
[scripts.eslint]
desc = "Auto cleaner"
commands = ["npx eslint ./ts/**/*.ts --fix"]
[script.prepare]
desc = "Prepare Husky"
commands = ["npx husky"]
[scripts.cleaner]
desc = "Delete unused files and folders"
commands = ["node ./scripts/cleaner.js"]

[copyright]
license = "apache"
year = "2026"
owner = "SoTeen Studio"
