target_dir = "src"
entry_file = "lib.rs"

[scripts.format]
desc = "Perform formatting on the code"
commands = ["clean", "header", "cargo fmt --all"]
[scripts.check]
desc = "Perform a check on the code"
commands = ["cargo clippy -- -D warnings"]
[scripts.perf]
desc = "Checking code performance"
commands = ["clean", "header", "track"]

[copyright]
license = "apache"
year = "2026"
owner = "SoTeen Studio"
