export type Instruction =
  | ["push", number | string | boolean | null | undefined]
  | ["val", string]
  | ["set", string]
  | ["get", string]
  | ["add", string]
  | ["sub", string]
  | ["mul"]
  | ["div"]
  | ["mod"]
  | ["gt"]
  | ["lt"]
  | ["ge"]
  | ["le"]
  | ["eq"]
  | ["neq"]
  | ["and"]
  | ["or"]
  | ["print"]
  | ["println"]
  | ["error"]
  | ["errorln"]
  | ["if_false", number]
  | ["jump", number]
  | ["inc", string]
  | ["dec", string]
  | ["call", string, number]
  | ["func", string, number, number, number, ...(string[] | [])]
  | ["stop"]
  | ["return"]
  | ["break"]
  | ["access", string]
  | ["access_index"]
  | ["string"]
  | ["number"]
  | ["make_obj", number]
  | ["make_array", number]
  | ["typeof"]
  | ["length"]
  | ["concat"]
  | ["dup"]
  | ["set_prop", string]
  | ["import", string, string]
  | ["export", string]
  | ["instantiate", string, number]