name: Sync Git Stats to Gist

concurrency:
  group: gist-stats-update
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Update Gist
        run: bash .github/scripts/stats/fetch_update_gist.sh
